### ISSUE TITLE
Client fails to launch in IntelliJ

### ISSUE THREAD

**Issue by colourfullyy** [Hexeption/MCP-Reborn#146] opened 2021-11-11 23:16 UTC
Hi, I've been trying to launch my game using the runclient gradle task, but it crashes after a few seconds.
**System information**
OS: Mac OS 12 Big Sur on apple M1
Azul Java 16 arm64.

Here's the log:
https://ghostbin.com/uVRd5

I would appreciate any help, thanks!

**Comment by kingdevnl** [comment] 2021-11-13 18:04
What version of MCP-Reborn and minecraft?

**Comment by colourfullyy** [comment] 2021-11-13 20:06
I'm using 1.17.1 mcp and minecraft. I'm quite sure it's the lack of native lwjgl libraries but I have no idea how to change them.

**Comment by stingalleman** [comment] 2021-12-14 18:38
@kingdevnl @Hexeption The issue is arm64/M1. Fabric has a fix for this issue (https://github.com/FabricMC/fabric-loom/issues/426#issuecomment-878204323), but how would I go about setting the natives using MCP?

**Comment by colourfullyy** [comment] 2021-12-28 22:57
I've figured out where the natives are located, you must generate the sources and run the game once to get access to the folder: {mcp-folder}/build/natives. I deleted everything in that folder, then copied minecraft's natives (arm64) from: https://github.com/yusefnapora/m1-multimc-hack/tree/master/lwjglnatives

However now the game doesn't launch, but instead crashes with this error/log:
[17:24:11] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[17:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.SystemReport.setDetail(SystemReport.java:62)
[17:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.fillSystemReport(Minecraft.java:2264)
[17:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2257)
[17:24:11] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:178)
[17:24:11] [Render thread/INFO]: [STDERR]: 	at mcp.client.Start.main(Start.java:17)

I'm not sure if the natives are correct, though I've used them with multimc so they should somewhat work.

**Comment by kingdevnl** [comment] 2021-12-29 15:02
@colourfullyy arm64 isn't really supported by minecraft
The game uses some openGL features that ain't on arm.

**Comment by stingalleman** [comment] 2022-02-12 17:59
@Hexeption Hi, is this fixed?

**Closed** 2022-02-12 17:58 UTC

**Comment by AdrianR3** [comment] 2022-02-28 00:44
I'm having the same issue. Was this fixed? 

> Exception in thread "Render thread" [16:38:13] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[16:38:13] [Render thread/INFO]: [STDERR]: at net.minecraft.SystemReport.setDetail(SystemReport.java:62)
[16:38:13] [Render thread/INFO]: [STDERR]: at net.minecraft.client.Minecraft.fillSystemReport(Minecraft.java:2264)
[16:38:13] [Render thread/INFO]: [STDERR]: at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2257)
[16:38:13] [Render thread/INFO]: [STDERR]: at net.minecraft.client.main.Main.main(Main.java:178)

I created a separate issue: #182

**Comment by anfanik** [comment] 2022-04-25 09:48
Run client with x86 JVM (you can download it in IDEA JDKs menu) It's works for me

My JVM:
<img width="575" alt="Screenshot 2022-04-25 at 11 47 22" src="https://user-images.githubusercontent.com/38406703/165064874-66f54a10-403d-46a2-9eb3-b295cabb75ae.png">
